#!/bin/sh

RESP=$(cat <<EOF | fzf
Lock
Logout
Sleep
Reboot
Shutdown
EOF
);

case "$RESP" in
	Lock)
		$HOME/.config/sway/lock.sh
		;;
	Logout)
		swaymsg exit
		;;
	Sleep)
		$HOME/.config/sway/lock.sh;
		systemctl suspend
		;;
	Reboot)
		systemctl reboot
		;;
	Shutdown)
		systemctl poweroff
		;;
	*)
		exit 1
esac
